name: finalyearproject
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=openblas
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.1.31=hf0a4a13_0
  - faiss=1.9.0=py311hc0156c1_0_cpu
  - fonttools=4.51.0=py311h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - jpeg=9e=h80987f9_3
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcxx=20.1.2=ha82da77_0
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.7.0=h286801f_0
  - libfaiss=1.9.0=h682f5e0_0_cpu
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libsqlite=3.46.0=hfb93653_0
  - libtiff=4.5.1=hc9ead59_1
  - libwebp-base=1.3.2=h80987f9_1
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=20.1.2=hdb05f8b_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.9.2=py311hca03da5_1
  - matplotlib-base=3.9.2=py311h7ef442a_1
  - ncurses=6.4=h313beb8_0
  - numpy=1.26.4=py311he598dae_0
  - numpy-base=1.26.4=py311hfbfe69c_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.5.0=h81ee809_0
  - pip=24.2=py311hca03da5_0
  - python=3.11.8=hdf0ec26_0_cpython
  - python_abi=3.11=6_cp311
  - readline=8.2=h1a28f6b_0
  - setuptools=75.1.0=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - unicodedata2=15.1.0=py311h80987f9_0
  - wheel=0.44.0=py311hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.6=hfb09047_0
  - pip:
      - accelerate==1.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.7.0
      - attrs==24.2.0
      - black==24.10.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.21.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.0
      - eval-type-backport==0.2.2
      - faiss-cpu==1.9.0.post1
      - fastapi==0.115.6
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gguf==0.10.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.26.5
      - idna==3.10
      - importlib-metadata==8.5.0
      - iniconfig==2.1.0
      - interegular==0.3.3
      - jinja2==3.1.4
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.5
      - lark==1.2.2
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.18.6
      - mteb==1.36.30
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.60.0
      - nvidia-ml-py==12.560.30
      - openai==1.57.4
      - opencv-python-headless==4.10.0.84
      - packaging==24.0
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post4
      - pathspec==0.12.1
      - pillow==10.3.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - polars==1.25.2
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.0
      - propcache==0.2.1
      - protobuf==5.29.1
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==18.1.0
      - pycountry==24.6.1
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pygments==2.19.1
      - pyparsing==3.1.2
      - pytest==8.3.5
      - python-dateutil==2.9.0
      - python-dotenv==1.0.1
      - pytrec-eval-terrier==0.5.6
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.22.3
      - safetensors==0.4.5
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - sentence-transformers==3.3.1
      - sentencepiece==0.2.0
      - six==1.16.0
      - sniffio==1.3.1
      - starlette==0.41.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.21.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.4
      - tqdm==4.67.1
      - transformers==4.47.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - watchfiles==1.0.3
      - websockets==14.1
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /opt/anaconda3/envs/finalyearproject
